version: '3'
services:
  my-mongodb:
    container_name: my-mongodb
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - ./data/db:/data/db
    networks:
      - nw
  app:
    build:
      context: .
      dockerfile: Dockerfile
    privileged: true
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATA_MONGODB_DATABASE=library
      - SPRING_DATA_MONGODB_PORT=27017
      - SPRING_DATA_MONGODB_HOST=my-mongodb
    networks:
      - nw
    depends_on:
      - my-mongodb
networks:
  nw:
