spring:
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1
    username: sa
    password:
    driver-class-name: org.h2.Driver
  flyway:
    enabled: true
    locations: classpath:db/schema, classpath:db/data
  jpa:
    hibernate:
      use-new-id-generator-mappings: true
      ddl-auto: validate
    show-sql: true
  data:
    mongodb:
      database: mongo_library
      port: 27017
      host: localhost
  batch:
    job:
      enabled: false
